name: CI
on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build JNI lib for ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build: x86_64-linux
            os: ubuntu-latest
#            docker: true
#          - build: aarch64-linux
#            os: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
#            docker: true
          - build: x86_64-macos
            os: macos-latest
          - build: aarch64-macos
            os: macos-latest
            target: aarch64-apple-darwin
          - build: x86_64-windows
            os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-2023-10-05
          override: true
          components: rustfmt
      - name: Set build target for cross-compiling
        if: matrix.target != ''
        run: |
          echo CARGO_BUILD_TARGET=${{ matrix.target }} >> build_env.txt
          echo JNILIB_RUST_TARGET=${{ matrix.target }} >> build_env.txt
          echo GRADLE_ARGS="${GRADLE_ARGS} -x test">> build_env.txt
          cat build_env.txt >> $GITHUB_ENV
          rustup target add ${{ matrix.target }}

      # Run gradle in a docker container to build the JNI lib on Linux for old glibc compatibility
      - name: Build with Gradle (Linux)
        if: ${{ matrix.docker }}
        run: |
          if [ ! -e build_env.txt ]; then
            touch build_env.txt
          fi
          docker build -t build-image ./ci/docker/${{ matrix.build }}
          docker run --rm --volume $PWD:/build --workdir /build \
            --env-file build_env.txt \
            build-image \
            ./gradlew build copyJniLib -x javadoc ${GRADLE_ARGS}

      # Otherwise, run gradle normally to build the JNI lib
      - name: Build with Gradle
        if: ${{ !matrix.docker }}
        run: ./gradlew build copyJniLib ${GRADLE_ARGS}

      - name: List shared library files
        run:
          file build/jni-libs/*

      - name: Save JNI lib output
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: jni-libs
          path: build/jni-libs/*
